language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - GUZZLE="~5.0"
        - SYMFONY_EVENT_DISPATCHER="~2.0"
    - php: 5.5
      env:
        - GUZZLE="~5.0"
        - SYMFONY_EVENT_DISPATCHER="~2.0"
    - php: 5.6
      env:
        - GUZZLE="~5.0"
        - SYMFONY_EVENT_DISPATCHER="~2.0"
    - php: 5.6
      env:
        - GUZZLE="~6.0"
        - SYMFONY_EVENT_DISPATCHER="~2.0"
    - php: 7.0
      env:
        - GUZZLE="~6.0"
        - SYMFONY_EVENT_DISPATCHER="~2.0"
    - php: 7.0
      env:
        - GUZZLE="~6.0"
        - SYMFONY_EVENT_DISPATCHER="~2.0"

before_install:
  - if [[ $GUZZLE != '' ]]; then composer require --no-update "guzzlehttp/guzzle:$GUZZLE" ; fi
  - if [[ $SYMFONY_EVENT_DISPATCHER != '' ]]; then composer require --no-update "symfony/event-dispatcher:$SYMFONY_EVENT_DISPATCHER" ; fi

install:
  - composer selfupdate
  - composer install --no-interaction

addons:
  code_climate:
    repo_token: 303a289e61e8e11d8bcae115860c4fffc6e1e7fe2d504d20a773e69bd7641284

after_script:
  - vendor/bin/test-reporter
